export const SEARCH_COUNTRY_SET = 'SEARCH_COUNTRY_SET';
export const SEARCH_MBID_SET = 'SEARCH_MBID_SET'
export const SEARCHED_TOP_ARTISTS = 'SEARCHED_TOP_ARTISTS';
export const RECEIVED_TOP_ARTISTS = 'RECEIVED_TOP_ARTISTS';
export const REQUESTED_TOP_ALBUMS = 'REQUESTED_TOP_ALBUMS';
export const RECEIVED_TOP_ALBUMS = 'RECEIVED_TOP_ALBUMS';
export const CLEARED_SEARCH_RESULTS = 'CLEARED_SEARCH_RESULTS';
